EasyPay.Api.sln
EasyPay.Api/Controllers/HomeController.cs
EasyPay.Api/EasyPay.Api.csproj
EasyPay.Api/Program.cs
EasyPay.Api/Properties/launchSettings.json
EasyPay.Api/Startup.cs
EasyPay.Api/appsettings.json

INFRA: Initialize Project

---

EasyPay.Api.Tests.Unit/DeleteMe.cs
EasyPay.Api.Tests.Unit/EasyPay.Api.Tests.Unit.csproj
EasyPay.Api.sln

INFRA: Initialize Unit Test

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Accounts.cs
EasyPay.Api/Brokers/Storages/IStorageBroker.Clients.cs
EasyPay.Api/Brokers/Storages/IStorageBroker.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Clients.cs
EasyPay.Api/Brokers/Storages/StorageBroker.cs

BROKERS: Insert Client

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Clients.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Clients.cs
EasyPay.Api/Brokers/Storages/StorageBroker.cs

BROKERS: Select All Clients

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Clients.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Clients.cs
EasyPay.Api/Brokers/Storages/StorageBroker.cs

BROKERS: Select By Id Client

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Clients.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Clients.cs
EasyPay.Api/Brokers/Storages/StorageBroker.cs

BROKERS: Delete Client

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Accounts.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Accounts.cs

BROKERS: Insert Account

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Accounts.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Accounts.cs

BROKERS: Select All Accounts

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Accounts.cs
EasyPay.Api/Brokers/Storages/IStorageBroker.Clients.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Accounts.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Clients.cs

BROKERS: Select By Id Account

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Accounts.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Accounts.cs

BROKERS: Update Account

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Accounts.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Accounts.cs

BROKERS: Delete Account

---

EasyPay.Api/Models/Clients/Client.cs
EasyPay.Api/Models/Clients/Exceptions/InvalidClientException.cs
EasyPay.Api/Models/Clients/Exceptions/NullClientException.cs
EasyPay.Api/Services/Foundations/Clients/ClientService.Validations.cs
EasyPay.Api/Services/Foundations/Clients/ClientService.cs
EasyPay.Api/Services/Foundations/Clients/IClientService.cs

FOUNDATIONS: Add Client & Validation

---

EasyPay.Api/Services/Foundations/Clients/ClientService.Validations.cs

CODE RUB: Refactor Code

---

EasyPay.Api/Models/Accounts/Exceptions/AccountDependencyException.cs
EasyPay.Api/Models/Accounts/Exceptions/AccountDependencyValidationException.cs
EasyPay.Api/Models/Accounts/Exceptions/AccountNotNull.cs
EasyPay.Api/Models/Accounts/Exceptions/AccountServiceException.cs
EasyPay.Api/Models/Accounts/Exceptions/AccountValidationException.cs
EasyPay.Api/Models/Accounts/Exceptions/AlreadyExistsAccountException.cs
EasyPay.Api/Models/Accounts/Exceptions/FailedAccountServiceException.cs
EasyPay.Api/Models/Accounts/Exceptions/FailedStorageAccountException.cs
EasyPay.Api/Models/Accounts/Exceptions/InvalidAccountException.cs
EasyPay.Api/Models/Accounts/Exceptions/LockedAccountException.cs
EasyPay.Api/Services/Foundations/Accounts/AccountService.Exceptions.cs
EasyPay.Api/Services/Foundations/Accounts/AccountService.Validations.cs
EasyPay.Api/Services/Foundations/Accounts/AccountService.cs
EasyPay.Api/Services/Foundations/Accounts/IAccountService.cs

POC: Add Account (WIP)

---

EasyPay.Api.Tests.Unit/Services/Foundations/Accounts/AccountServiceTests.Logic.Add.cs
EasyPay.Api.Tests.Unit/Services/Foundations/Accounts/AccountServiceTests.cs
EasyPay.Api.Tests.Unit/Services/Foundations/Clients/ClientServiceTests.Validations.Add.cs
EasyPay.Api/Services/Foundations/Accounts/AccountService.Exceptions.cs
EasyPay.Api/Services/Foundations/Accounts/AccountService.cs

POC: Add Account

---

EasyPay.Api.Tests.Unit/Services/Foundations/Clients/ClientServiceTests.Exceptions.RetrieveAll.cs
EasyPay.Api/Services/Foundations/Clients/ClientService.Exceptions.cs

FOUNDATIONS: Retrieve All Clients

---

EasyPay.Api.Tests.Unit/Services/Foundations/Accounts/AccountServiceTests.Exceptions.RetrieveById.cs
EasyPay.Api.Tests.Unit/Services/Foundations/Accounts/AccountServiceTests.Logic.RetrieveById.cs
EasyPay.Api.Tests.Unit/Services/Foundations/Accounts/AccountServiceTests.Validations.RetrieveById.cs
EasyPay.Api/Models/Accounts/Exceptions/NotFoundAccountException.cs
EasyPay.Api/Services/Foundations/Accounts/AccountService.Exceptions.cs
EasyPay.Api/Services/Foundations/Accounts/AccountService.Validations.cs
EasyPay.Api/Services/Foundations/Accounts/AccountService.cs
EasyPay.Api/Services/Foundations/Accounts/IAccountService.cs

FOUNDATIONS: Retrieve Account By Id

---

EasyPay.Api/Controllers/ClientController.cs

CONTROLLERS: Get Client By Id

---

EasyPay.Api/Brokers/Storages/StorageBroker.Transfers.cs
EasyPay.Api/Migrations/20231021113616_CreateTransferTable.Designer.cs
EasyPay.Api/Migrations/20231021113616_CreateTransferTable.cs
EasyPay.Api/Models/Transfers/Transfer.cs

DATA: Transfer Model & Migrate

---

EasyPay.Api/Controllers/AccountController.cs

CONTROLLER: Post Account

---

EasyPay.Api/Migrations/20231022084226_FullTables.Designer.cs
EasyPay.Api/Migrations/20231022084226_FullTables.cs

DATA: Update Migration

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Transfers.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Transfers.cs
EasyPay.Api/Brokers/Storages/StorageBroker.cs

BROKERS: Select Account By Account Number

---

EasyPay.Api/Controllers/AccountController.cs
EasyPay.Api/Controllers/TransferController.cs
EasyPay.Api/Models/Transfers/Transfer.cs
EasyPay.Api/Services/Foundations/Transfers/TransferService.cs
EasyPay.Api/Startup.cs

POC: Add Transfer

---

EasyPay.Api/Brokers/Storages/IStorageBroker.Transfers.cs
EasyPay.Api/Brokers/Storages/StorageBroker.Transfers.cs

BROKERS: Add Transfer

---

EasyPay.Api/Models/Accounts/Exceptions/InsufficientFundsException.cs
EasyPay.Api/Models/Accounts/Exceptions/NotFoundAccountByAccountNumberException.cs
EasyPay.Api/Models/Transfers/Exceptions/InvalidTransferException.cs
EasyPay.Api/Services/Foundations/Transfers/TransferService.Validation.cs
EasyPay.Api/Services/Foundations/Transfers/TransferService.cs

POC: Add Transfer(WIP)

---

EasyPay.Api.Tests.Unit/Services/Foundations/Accounts/AccountServiceTests.Exceptions.Add.cs
EasyPay.Api.Tests.Unit/Services/Foundations/Accounts/AccountServiceTests.Exceptions.Modify.cs
EasyPay.Api.Tests.Unit/Services/Foundations/Accounts/AccountServiceTests.Exceptions.RemoveById.cs
EasyPay.Api.Tests.Unit/Services/Foundations/Accounts/AccountServiceTests.Validations.Modify.cs
EasyPay.Api.Tests.Unit/Services/Foundations/Clients/ClientServiceTests.Exception.Add.cs
EasyPay.Api.Tests.Unit/Services/Foundations/Clients/ClientServiceTests.Exception.RemoveById.cs
EasyPay.Api/Controllers/ClientController.cs

CONTROLLERS: Put Client

---

EasyPay.Api/Controllers/ClientController.cs

CONTROLLERS: Delete Client
